spring:
  datasource:
    url: jdbc:sqlserver://fsd09-server-2.database.windows.net:1433;database=dbfsd09-2;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: adminjactest2
    password: Password123*
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191